// Generated by CoffeeScript 1.4.0
var app, config, port;

app = require('app');

config = require('app/config');

port = process.env.PORT || process.env.VMC_APP_PORT || config.port || 5000;

app.listen(port, function() {
  return console.log('Listening on ' + port + '\nPress CTRL-C to stop server.');
});
