// Generated by CoffeeScript 1.4.0

module.exports = function(req, res, next) {
  req.app.locals({
    nextcore: {
      scheme: 'http',
      host: 'nextcore-test.homes.co.jp',
      port: 80,
      key: 'YzQxODRmOGFlODZhYjVhZTg0N2NjZjMz',
      secret: 'NTNhM2VkYzkwNGQ3NWRjNzM3ZDRkYjg1OWM0MTZjZTE5YmY4ZWNlMzVlNjBmZmViMThkOTlhZTJjNTE3NzA1Mw'
    }
  });
  return next();
};
