// Generated by CoffeeScript 1.4.0
var app, app_dir, assets, config, env, express, http, path, port, public_dir, routes, stylus, views_dir;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

http = require('http');

path = require('path');

routes = require('./routes');

app = express();

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

env = app.get('env');

app_dir = path.join(process.cwd(), 'app');

views_dir = path.join(process.cwd(), 'views');

public_dir = path.join(process.cwd(), 'public');

config = require(path.join(app_dir, 'config', env));

app.configure(function() {
  app.set('port', port);
  app.set('views', views_dir);
  app.set('view engine', 'jade');
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser('c1a36caa10c91e1bd2eed400d5a8717eea649573'));
  app.use(express.session());
  app.use(express["static"](public_dir));
  app.use(config);
  app.use(app.router);
  return app.use(assets());
});

app.configure('development', function() {
  return app.use(express.errorHandler());
});

routes.bootstrap(app);

http.createServer(app).listen(port, function() {
  return console.log("Listening on " + port + "\nEnv: " + env + "\nPress CTRL-C to stop server.");
});
