// Generated by CoffeeScript 1.4.0
var do_nothing, path;

path = require('path');

do_nothing = function(req, res) {
  return res.end();
};

exports.bootstrap = function(app) {
  var config, entries, name, _results;
  entries = require(path.join(__dirname, app.get('env')));
  _results = [];
  for (name in entries) {
    config = entries[name];
    _results.push((function(name, config) {
      var action, method, pattern, _ref;
      method = ((_ref = config.method) != null ? _ref.toLowerCase() : void 0) || 'get';
      pattern = config.pattern;
      action = config.action || do_nothing;
      return app[method](pattern, action);
    })(name, config));
  }
  return _results;
};

exports.generate = function(name, params) {
  return name;
};
