// Generated by CoffeeScript 1.4.0
var ALL, DELETE, GET, POST, PUT, _ref;

_ref = require('./util').verbs, GET = _ref[0], POST = _ref[1], PUT = _ref[2], DELETE = _ref[3], ALL = _ref[4];

module.exports = {
  index: GET('/', 'index'),
  api: ALL('/api/*', 'api')
};
