// Generated by CoffeeScript 1.4.0
var path, router;

path = require('path');

router = function(method) {
  return function(pattern, action_path) {
    return {
      method: method,
      pattern: pattern,
      action: require(path.join('../controllers', action_path))
    };
  };
};

exports.verbs = ['GET', 'POST', 'PUT', 'DELETE', 'ALL'].map(router);
