// Generated by CoffeeScript 1.4.0
var Path, http, querystring, urlsafe_base64;

http = require('http');

querystring = require('querystring');

Path = require('path');

urlsafe_base64 = require('text').urlsafeEncode64;

module.exports = function(req, res) {
  var host, method, path, query;
  host = req.app.locals.nextcore.host;
  path = Path.join('/', req.params[0]);
  method = req.method;
  query = querystring.stringify(req.query);
  console.log(method, host, path, query);
  return res.render('proxy');
};
